version: '3'
 
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - .db_data/db.sqlite3:/db.sqlite3
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"

  memcached:
    image: memcached:latest
    entrypoint:
      - memcached
      - -m 64
    expose:
      - "11211"
    depends_on:
      - app